production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: moodle_quiz_editor
  pool: 5
  username: root
  password: uclthesis
  host: localhost

development:
  adapter: sqlite3
  database: db/sqlite3:dev_moodle_quiz_editor.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/sqlite3:test_moodle_quiz_editor.db
  pool: 5
  timeout: 5000
